name:                gzc-lib
version:             0.1.0.0
github:              "zilch-lang/gzc"
license:             BSD3
author:              "Mesabloo"
copyright:           "2022 Mesabloo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zilch-lang/zilch#readme>

dependencies:
- base >= 4.7 && < 5
- text ==1.2.5.0
# - gzc-core
- megaparsec >=9.0 && <10
- mtl ==2.2.2
- diagnose >=2
- nsc-core
# - gzc-flags
# - algebraic-graphs >=0.6
# - containers ==0.6.*
# - filepath >=1.4
# - directory >=1.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

# executables:
#   gzc:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - gzc-lib

tests:
  parser-tests:
    main:                Spec.hs
    source-dirs:         test/Parser
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gzc-lib
    - text ==1.2.5.0
    - pretty-simple
