name:                gzc-lib
version:             0.1.0.0
github:              "zilch-lang/gzc"
license:             BSD3
author:              "Mesabloo"
copyright:           "2022 Mesabloo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zilch-lang/zilch#readme>

when:
  - condition: flag(liquidhaskell)
    then:
      dependencies:
      - liquidhaskell == 0.8.10.7.1
      - liquid-base == 4.14.3.0
      - liquid-ghc-prim 
      - liquid-fixpoint
      - liquid-prelude
      ghc-options:
      - -fplugin=LiquidHaskell
      # - -fplugin-opt=LiquidHaskell:...
    else:
      dependencies:
      - base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - text ==1.2.5.0
  # - gzc-core
  - megaparsec >=9.0 && <10
  - mtl ==2.2.2
  - diagnose >=2
  - nsc-core
  # - gzc-flags
  # - algebraic-graphs >=0.6
  # - containers ==0.6.*
  # - filepath >=1.4
  # - directory >=1.3

flags:
  liquidhaskell:
    description: "Enable verification of some source files with LiquidHaskell"
    default: false
    manual: true

executables:
  gzc:
    main:                Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-unused-matches
    - -Wno-incomplete-patterns
    - -Wno-unused-imports
    - -Wno-missing-signatures
    - -Wno-unused-top-binds
    - -Wno-redundant-constraints
    - -Wno-name-shadowing
    dependencies:
    - gzc-lib
    - diagnose
    - filepath >=1.4
    - directory >=1.3
    - megaparsec >=9.0 && <10
    - optparse-applicative >=0.16
    - nsc-core
    - text ==1.2.5.0
    - mtl ==2.2.2
    default-extensions:
    - TypeSynonymInstances
    - FlexibleInstances

tests:
  parser-tests:
    main:                Spec.hs
    source-dirs:         test/Parser
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gzc-lib
    - text ==1.2.5.0
    - pretty-simple
