name:                gzc-lib
version:             !include "version.yaml"
github:              "zilch-lang/zilch"
license:             BSD3
author:              "Mesabloo"
copyright:           "2021 Mesabloo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zilch-lang/gzc#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wextra

default-extensions: !include "default-extensions.yaml"

library:
  source-dirs: src

executables:
  gzc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gzc-lib

tests:
  gzc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gzc-lib
