open import vec::{vec3::*, vec4::*}


public record material :=
  constructor material

  public val refractive_index : f32
  public val albedo : vec4f
  public val diffuse_color : vec3f
  public val specular_exponent : f32


public let glass :=
  material 1.5
           (vec4 0.0 0.5 0.1 0.8)
           (vec3 0.6 0.7 0.8)
           125.0

public let ivory :=
  material 1.0
           (vec4 0.6 0.3 0.1 0.0)
           (vec3 0.4 0.4 0.3)
           50.0
