/-- 
  fact : (n : nat) -> nat
  ---

  Computes the factorial of the given parameter `n` (denoted as `n!`).

  Equivalent to the formula $$
    \begin{equation}
      0! &= 1 \\
      1! &= 1 \\
      n! &= n * (n - 1)!
    \end{equation}
  $$ but implemented more efficiently using tail calls.
-/
public let fact
  : nat -> nat :=

  #attributes(inline)
  let aux 
    (acc : nat) (n : nat)
    : nat :=
    
    match n with
      0 | 1 => acc 
      _     => aux (acc * n) (n - 1)

  aux 1
